### ISSUE TITLE
class simulation 

### ISSUE THREAD

**Issue by ninawahler** [EPFL-SV-cpp-projects/Team_1#6]
Create a class simulation in order to run a certain number of generations

**Comment by gan74** [comment]
[il y a un memory leak](https://github.com/EPFL-SV-cpp-projects/Team_1/blob/d88ee33dbbe7103979db06462ee86f94d5253ed7/src/Simulation.cpp#L28)

**Comment by RibaultEPFL** [comment]
résolu normalement
